services:

  # Setup The Backend Service
  backend:
    build: ./backend
    ports:
    - "8080:8080"
    tty: true
    environment:
      - DB_ADDRESS=jdbc:mysql://mysql:3306
      - DB_DATABASE=stockbot_db
      - DB_USER=root
      - DB_PASSWORD=pwd
    networks:
      - backend-mysql
      - backend-frontend
      - backend-discord
  # Setup The SQL Service
  mysql:
    build: ./database
    ports:
    - "3306:3306"
    environment:
      # Mysql docker image env vars
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=stockbot_db
    volumes:
     - mariadb_data:/var/lib/database  # Maps 'mariadb_data' volume to the data directory of MySQ
    networks:
    - backend-mysql
    - scraper-mysql
    depends_on:
      - scraper

  # Setup The Scraper Service
  scraper:
    build: ./Scraper
    env_file: ${PWD}/.env
    environment:
      - DB_ADDRESS=mysql
      - DB_DATABASE=stockbot_db
      - DB_USER=root
      - DB_PASSWORD=pwd
    networks:
      - scraper-mysql
      - scraper-selenium
  # Setup The Discord Service
  discord:
    build: ./discordBot

    env_file: ${PWD}/.env

    networks:
      - backend-discord

  # Setup The Selenium Service
  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - scraper-selenium
      
volumes:
  mariadb_data:  # Defines a named volume 'mariadb_data' for the MySQL service to use for data persistence
networks:
  backend-mysql:
  backend-frontend:
  backend-discord:
  scraper-mysql:
  scraper-selenium: