services:
  python:
    build: ./python

    networks: 
      - spring-python

  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - spring-python

networks:
  spring-python: